# serverless.yml
service: laravel-api

provider:
  name: aws
  region: us-east-1
  runtime: php-82-fpm # ✅ Cambiado a PHP 8.2
  stage: dev
  versionFunctions: true
  deploymentMethod: direct

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: public/index.php
    description: "Laravel API"
    runtime: php-82-fpm # ✅ Usamos la versión correcta de PHP
    # runtime: provided.al2
    timeout: 70
    memorySize: 2048
    # layers:
    #   - ${bref:layer.php-82-fpm}

    events:
      - httpApi: "*"
    environment:
      APP_NAME: ${env:APP_NAME}
      APP_ENV: production
      APP_KEY: ${env:APP_KEY}
      APP_DEBUG: false
      APP_TIMEZONE: UTC
      APP_URL: ${env:APP_URL}
      APP_LOCALE: ${env:APP_LOCALE}
      APP_FALLBACK_LOCALE: ${env:APP_FALLBACK_LOCALE}
      APP_FAKER_LOCALE: ${env:APP_FAKER_LOCALE}
      APP_MAINTENANCE_DRIVER: ${env:APP_MAINTENANCE_DRIVER}
      BCRYPT_ROUNDS: ${env:BCRYPT_ROUNDS}

      LOG_CHANNEL: ${env:LOG_CHANNEL}
      LOG_STACK: ${env:LOG_STACK}
      LOG_DEPRECATIONS_CHANNEL: ${env:LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${env:LOG_LEVEL}

      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_DATABASE: ${env:DB_DATABASE}
      DB_USERNAME: ${env:DB_USERNAME}
      DB_PASSWORD: ${env:DB_PASSWORD}

      SESSION_DRIVER: ${env:SESSION_DRIVER}
      SESSION_LIFETIME: ${env:SESSION_LIFETIME}
      SESSION_ENCRYPT: ${env:SESSION_ENCRYPT}
      SESSION_PATH: ${env:SESSION_PATH}
      SESSION_DOMAIN: ${env:SESSION_DOMAIN}

      # BROADCAST_CONNECTION: ${env:BROADCAST_CONNECTION}
      # FILESYSTEM_DISK: ${env:FILESYSTEM_DISK}
      # QUEUE_CONNECTION: ${env:QUEUE_CONNECTION}
      # CACHE_STORE: ${env:CACHE_STORE}
      # CACHE_PREFIX: ${env:CACHE_PREFIX}

      # MAIL_MAILER: ${env:MAIL_MAILER}
      # MAIL_HOST: ${env:MAIL_HOST}
      # MAIL_PORT: ${env:MAIL_PORT}
      # MAIL_USERNAME: ${env:MAIL_USERNAME}
      # MAIL_PASSWORD: ${env:MAIL_PASSWORD}
      # MAIL_ENCRYPTION: ${env:MAIL_ENCRYPTION}
      # MAIL_FROM_ADDRESS: ${env:MAIL_FROM_ADDRESS}
      # MAIL_FROM_NAME: ${env:MAIL_FROM_NAME}

      # Eliminadas variables reservadas de AWS
      # AWS_ACCESS_KEY_ID
      # AWS_SECRET_ACCESS_KEY
      # AWS_DEFAULT_REGION
      # AWS_BUCKET: ${env:AWS_BUCKET}
      # AWS_USE_PATH_STYLE_ENDPOINT: ${env:AWS_USE_PATH_STYLE_ENDPOINT}

      FASTAPI_SHARED_SECRET: ${env:FASTAPI_SHARED_SECRET}
      FASTAPI_BASE_URL: ${env:FASTAPI_BASE_URL}
      PYTHON_SERVICE_URL: ${env:PYTHON_SERVICE_URL}

      PHP_FPM_LOG_LEVEL: "notice" # Añade esto

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!storage/logs/**"
    - "!.env.example"
    - "!README.md"
    - "!docker*"
    - "!phpunit.xml"
